import React, { useState } from 'react'
import { motion } from 'framer-motion'
import { Copy, Download, Eye, Code, CheckCircle } from 'lucide-react'
import toast from 'react-hot-toast'
import ReactMarkdown from 'react-markdown'
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter'
import { oneDark } from 'react-syntax-highlighter/dist/esm/styles/prism'

const ArtifactViewer = ({ artifact }) => {
  const [viewMode, setViewMode] = useState('rendered')
  const [copied, setCopied] = useState(false)

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(artifact.content)
      setCopied(true)
      toast.success('Content copied to clipboard')
      setTimeout(() => setCopied(false), 2000)
    } catch (error) {
      toast.error('Failed to copy content')
    }
  }

  const handleDownload = () => {
    const blob = new Blob([artifact.content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${artifact.name.replace(/\s+/g, '_')}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success('File downloaded')
  }

  const renderContent = () => {
    if (viewMode === 'raw') {
      return (
        <pre className="whitespace-pre-wrap text-sm text-secondary-700 font-mono bg-secondary-50 p-4 rounded-lg overflow-auto max-h-96">
          {artifact.content}
        </pre>
      )
    }

    // Render as markdown
    return (
      <div className="prose prose-secondary max-w-none">
        <ReactMarkdown
          components={{
            code({ node, inline, className, children, ...props }) {
              const match = /language-(\w+)/.exec(className || '')
              return !inline && match ? (
                <SyntaxHighlighter
                  style={oneDark}
                  language={match[1]}
                  PreTag="div"
                  className="rounded-lg"
                  {...props}
                >
                  {String(children).replace(/\n$/, '')}
                </SyntaxHighlighter>
              ) : (
                <code className={className} {...props}>
                  {children}
                </code>
              )
            }
          }}
        >
          {artifact.content}
        </ReactMarkdown>
      </div>
    )
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="card"
    >
      {/* Header */}
      <div className="flex items-center justify-between mb-6 pb-4 border-b border-secondary-200">
        <div>
          <h3 className="text-lg font-semibold text-secondary-900">
            {artifact.name}
          </h3>
          <p className="text-sm text-secondary-600 mt-1">
            Generated by {artifact.agent_role.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase())}
          </p>
        </div>
        
        <div className="flex items-center space-x-2">
          {/* View Mode Toggle */}
          <div className="flex rounded-lg border border-secondary-200 overflow-hidden">
            <button
              onClick={() => setViewMode('rendered')}
              className={`px-3 py-1 text-sm font-medium transition-colors ${
                viewMode === 'rendered'
                  ? 'bg-primary-600 text-white'
                  : 'text-secondary-600 hover:text-secondary-900'
              }`}
            >
              <Eye className="h-4 w-4 mr-1 inline" />
              Rendered
            </button>
            <button
              onClick={() => setViewMode('raw')}
              className={`px-3 py-1 text-sm font-medium transition-colors ${
                viewMode === 'raw'
                  ? 'bg-primary-600 text-white'
                  : 'text-secondary-600 hover:text-secondary-900'
              }`}
            >
              <Code className="h-4 w-4 mr-1 inline" />
              Raw
            </button>
          </div>
          
          {/* Actions */}
          <button
            onClick={handleCopy}
            className="btn-outline p-2"
            title="Copy to clipboard"
          >
            {copied ? (
              <CheckCircle className="h-4 w-4 text-success-600" />
            ) : (
              <Copy className="h-4 w-4" />
            )}
          </button>
          
          <button
            onClick={handleDownload}
            className="btn-outline p-2"
            title="Download file"
          >
            <Download className="h-4 w-4" />
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="max-h-96 overflow-auto">
        {renderContent()}
      </div>
    </motion.div>
  )
}

export default ArtifactViewer