import React, { useState, useEffect, useRef } from 'react'
import { motion } from 'framer-motion'
import { 
  Play, Square, RotateCcw, ExternalLink, Download, 
  Terminal, Globe, Code, FileText, Loader, AlertCircle,
  CheckCircle, Maximize2, Minimize2, Info
} from 'lucide-react'

// Get E2B API key safely
const getE2BApiKey = () => {
  try {
    return import.meta.env.VITE_E2B_API_KEY || 
           (typeof process !== 'undefined' && process.env?.REACT_APP_E2B_API_KEY) ||
           (typeof window !== 'undefined' && window.ENV?.E2B_API_KEY)
  } catch (err) {
    console.warn('Could not access environment variables:', err)
    return null
  }
}

const E2BSandboxPreview = ({ 
  artifacts = [], 
  generationId,
  onSandboxReady,
  onPreviewUpdate 
}) => {
  const [sandbox, setSandbox] = useState(null)
  const [isLoading, setIsLoading] = useState(false)
  const [isRunning, setIsRunning] = useState(false)
  const [previewUrl, setPreviewUrl] = useState(null)
  const [logs, setLogs] = useState([])
  const [error, setError] = useState(null)
  const [activeTab, setActiveTab] = useState('preview')
  const [isExpanded, setIsExpanded] = useState(false)
  const [filesCreated, setFilesCreated] = useState([])
  
  const iframeRef = useRef(null)
  const logsRef = useRef(null)

  // Auto-scroll logs
  useEffect(() => {
    if (logsRef.current) {
      logsRef.current.scrollTop = logsRef.current.scrollHeight
    }
  }, [logs])

  // Initialize E2B sandbox
  const initializeSandbox = async () => {
    const apiKey = getE2BApiKey()
    
    if (!apiKey) {
      setError('E2B API key not configured. Please set VITE_E2B_API_KEY in your environment.')
      return
    }

    setIsLoading(true)
    setError(null)
    
    try {
      // Import E2B dynamically
      const { CodeInterpreter } = await import('@e2b/code-interpreter')
      
      const newSandbox = await CodeInterpreter.create({
        apiKey: apiKey,
        metadata: {
          generationId: generationId
        }
      })
      
      setSandbox(newSandbox)
      addLog('✅ E2B sandbox initialized successfully')
      
      if (onSandboxReady) {
        onSandboxReady(newSandbox)
      }
      
    } catch (err) {
      console.error('Failed to initialize E2B sandbox:', err)
      setError(`Failed to initialize sandbox: ${err.message}`)
      addLog(`❌ Sandbox initialization failed: ${err.message}`)
    } finally {
      setIsLoading(false)
    }
  }

  // Add log entry
  const addLog = (message) => {
    const timestamp = new Date().toLocaleTimeString()
    setLogs(prev => [...prev, `[${timestamp}] ${message}`])
  }

  // Create files from artifacts
  const createFiles = async () => {
    if (!sandbox || artifacts.length === 0) return

    setIsLoading(true)
    addLog('📁 Creating files from generated artifacts...')
    
    try {
      const createdFiles = []
      
      for (const artifact of artifacts) {
        const filename = getFilenameFromArtifact(artifact)
        
        await sandbox.files.write(filename, artifact.content)
        createdFiles.push(filename)
        addLog(`📄 Created: ${filename}`)
      }
      
      setFilesCreated(createdFiles)
      addLog(`✅ Created ${createdFiles.length} files successfully`)
      
    } catch (err) {
      console.error('Failed to create files:', err)
      setError(`Failed to create files: ${err.message}`)
      addLog(`❌ File creation failed: ${err.message}`)
    } finally {
      setIsLoading(false)
    }
  }

  // Get appropriate filename from artifact
  const getFilenameFromArtifact = (artifact) => {
    const name = artifact.name.toLowerCase().replace(/\s+/g, '_')
    
    // Map artifact types to file extensions
    const extensionMap = {
      'product requirements document': 'requirements.md',
      'system architecture design': 'architecture.md',
      'project plan & timeline': 'project_plan.md',
      'technical implementation': 'implementation.md',
      'test strategy & cases': 'test_strategy.md',
      'deployment & infrastructure': 'deployment.md'
    }
    
    return extensionMap[artifact.name.toLowerCase()] || `${name}.md`
  }

  // Run the generated application
  const runApplication = async () => {
    if (!sandbox || filesCreated.length === 0) return

    setIsRunning(true)
    setError(null)
    addLog('🚀 Starting application...')
    
    try {
      // For now, create a simple documentation viewer
      const streamlitCode = `
import streamlit as st

st.title("🚀 Generated Application Documentation")
st.write("This application was generated by AI agents!")

# Display generated artifacts
st.header("Generated Documentation")
${artifacts.map(artifact => `
st.subheader("${artifact.name}")
st.markdown("""${artifact.content.replace(/"/g, '\\"')}""")
`).join('\n')}
`
      
      await sandbox.files.write('streamlit_app.py', streamlitCode)
      await sandbox.commands.run('pip install streamlit')
      await sandbox.commands.run('streamlit run streamlit_app.py --server.port 8501 &')
      
      const hostname = await sandbox.getHostname(8501)
      const url = `https://${hostname}`
      setPreviewUrl(url)
      
      addLog(`✅ Documentation viewer running at: ${url}`)
      
      if (onPreviewUpdate) {
        onPreviewUpdate({ type: 'documentation', url })
      }
      
    } catch (err) {
      console.error('Failed to run application:', err)
      setError(`Failed to run application: ${err.message}`)
      addLog(`❌ Application failed to start: ${err.message}`)
    } finally {
      setIsRunning(false)
    }
  }

  // Stop the application
  const stopApplication = () => {
    setIsRunning(false)
    setPreviewUrl(null)
    addLog('🛑 Application stopped')
  }

  // Restart the application
  const restartApplication = async () => {
    stopApplication()
    await new Promise(resolve => setTimeout(resolve, 1000))
    await runApplication()
  }

  // Download generated files
  const downloadFiles = async () => {
    if (filesCreated.length === 0) return

    addLog('📥 Preparing files for download...')
    
    try {
      // Create a simple download of all artifacts
      const zip = new JSZip()
      
      artifacts.forEach((artifact, index) => {
        const filename = getFilenameFromArtifact(artifact)
        zip.file(filename, artifact.content)
      })
      
      const blob = await zip.generateAsync({ type: 'blob' })
      const url = URL.createObjectURL(blob)
      
      const a = document.createElement('a')
      a.href = url
      a.download = `generated-app-${generationId}.zip`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
      
      addLog('✅ Files downloaded successfully')
      
    } catch (err) {
      console.error('Failed to download files:', err)
      addLog(`❌ Download failed: ${err.message}`)
    }
  }

  // Auto-create files when artifacts are available
  useEffect(() => {
    if (sandbox && artifacts.length > 0 && filesCreated.length === 0) {
      createFiles()
    }
  }, [sandbox, artifacts])

  if (!artifacts || artifacts.length === 0) {
    return (
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8">
        <div className="text-center">
          <Code className="h-12 w-12 text-gray-400 mx-auto mb-4" />
          <h3 className="text-lg font-medium text-gray-900 mb-2">
            No Artifacts Yet
          </h3>
          <p className="text-gray-600">
            Generated artifacts will appear here for live preview
          </p>
        </div>
      </div>
    )
  }

  return (
    <div className={`bg-white rounded-xl shadow-sm border border-gray-200 transition-all duration-300 ${
      isExpanded ? 'fixed inset-4 z-50' : 'h-96'
    }`}>
      {/* Header */}
      <div className="flex items-center justify-between p-4 border-b border-gray-200">
        <div className="flex items-center space-x-3">
          <div className="flex items-center space-x-2">
            <Globe className="h-5 w-5 text-blue-600" />
            <h3 className="font-semibold text-gray-900">Live Preview</h3>
          </div>
          
          {sandbox && (
            <div className="flex items-center space-x-1 text-sm text-green-600">
              <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse" />
              <span>Sandbox Active</span>
            </div>
          )}
        </div>
        
        <div className="flex items-center space-x-2">
          {/* Control Buttons */}
          {sandbox && (
            <>
              <button
                onClick={runApplication}
                disabled={isLoading || isRunning}
                className="btn-outline p-2"
                title="Run Application"
              >
                <Play className="h-4 w-4" />
              </button>
              
              <button
                onClick={stopApplication}
                disabled={!isRunning}
                className="btn-outline p-2"
                title="Stop Application"
              >
                <Square className="h-4 w-4" />
              </button>
              
              <button
                onClick={restartApplication}
                disabled={isLoading}
                className="btn-outline p-2"
                title="Restart Application"
              >
                <RotateCcw className="h-4 w-4" />
              </button>
              
              <button
                onClick={downloadFiles}
                disabled={filesCreated.length === 0}
                className="btn-outline p-2"
                title="Download Files"
              >
                <Download className="h-4 w-4" />
              </button>
            </>
          )}
          
          {previewUrl && (
            <a
              href={previewUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="btn-outline p-2"
              title="Open in New Tab"
            >
              <ExternalLink className="h-4 w-4" />
            </a>
          )}
          
          <button
            onClick={() => setIsExpanded(!isExpanded)}
            className="btn-outline p-2"
            title={isExpanded ? "Minimize" : "Maximize"}
          >
            {isExpanded ? <Minimize2 className="h-4 w-4" /> : <Maximize2 className="h-4 w-4" />}
          </button>
        </div>
      </div>

      {/* Error Display */}
      {error && (
        <div className="p-4 bg-red-50 border-b border-red-200">
          <div className="flex items-center space-x-2 text-red-800">
            <AlertCircle className="h-4 w-4" />
            <span className="text-sm font-medium">Error</span>
          </div>
          <p className="text-sm text-red-700 mt-1">{error}</p>
          
          {!sandbox && (
            <button
              onClick={initializeSandbox}
              className="mt-2 text-sm text-red-600 hover:text-red-800 underline"
            >
              Retry Initialization
            </button>
          )}
        </div>
      )}

      {/* Tab Navigation */}
      <div className="flex border-b border-gray-200">
        {['preview', 'logs', 'files'].map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`px-4 py-2 text-sm font-medium capitalize transition-colors ${
              activeTab === tab
                ? 'text-blue-600 border-b-2 border-blue-600'
                : 'text-gray-600 hover:text-gray-900'
            }`}
          >
            {tab === 'preview' && <Globe className="h-4 w-4 inline mr-1" />}
            {tab === 'logs' && <Terminal className="h-4 w-4 inline mr-1" />}
            {tab === 'files' && <FileText className="h-4 w-4 inline mr-1" />}
            {tab}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      <div className={`${isExpanded ? 'h-full' : 'h-80'} overflow-hidden`}>
        {/* Preview Tab */}
        {activeTab === 'preview' && (
          <div className="h-full">
            {isLoading && (
              <div className="h-full flex items-center justify-center">
                <div className="text-center">
                  <Loader className="h-8 w-8 animate-spin text-blue-600 mx-auto mb-2" />
                  <p className="text-gray-600">Initializing sandbox...</p>
                </div>
              </div>
            )}
            
            {previewUrl && !isLoading && (
              <iframe
                ref={iframeRef}
                src={previewUrl}
                className="w-full h-full border-0"
                title="Application Preview"
              />
            )}
            
            {!previewUrl && !isLoading && sandbox && (
              <div className="h-full flex items-center justify-center">
                <div className="text-center">
                  <Play className="h-12 w-12 text-gray-400 mx-auto mb-4" />
                  <h4 className="text-lg font-medium text-gray-900 mb-2">
                    Ready to Preview
                  </h4>
                  <p className="text-gray-600 mb-4">
                    Click the play button to start your application
                  </p>
                  <button
                    onClick={runApplication}
                    disabled={isRunning}
                    className="btn-primary"
                  >
                    <Play className="h-4 w-4 mr-2" />
                    Start Application
                  </button>
                </div>
              </div>
            )}
            
            {!sandbox && !isLoading && (
              <div className="h-full flex items-center justify-center">
                <div className="text-center">
                  <Info className="h-12 w-12 text-blue-400 mx-auto mb-4" />
                  <h4 className="text-lg font-medium text-gray-900 mb-2">
                    E2B Sandbox Required
                  </h4>
                  <p className="text-gray-600 mb-4">
                    Configure E2B API key to enable live previews
                  </p>
                  <button
                    onClick={initializeSandbox}
                    className="btn-primary"
                  >
                    Initialize Sandbox
                  </button>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Logs Tab */}
        {activeTab === 'logs' && (
          <div
            ref={logsRef}
            className="h-full p-4 bg-gray-900 text-green-400 font-mono text-sm overflow-y-auto"
          >
            {logs.length === 0 ? (
              <div className="text-gray-500">No logs yet...</div>
            ) : (
              logs.map((log, index) => (
                <div key={index} className="mb-1">
                  {log}
                </div>
              ))
            )}
          </div>
        )}

        {/* Files Tab */}
        {activeTab === 'files' && (
          <div className="h-full p-4 overflow-y-auto">
            {filesCreated.length === 0 ? (
              <div className="text-center text-gray-500 mt-8">
                <FileText className="h-8 w-8 mx-auto mb-2" />
                <p>No files created yet</p>
              </div>
            ) : (
              <div className="space-y-2">
                {filesCreated.map((filename, index) => (
                  <div
                    key={index}
                    className="flex items-center space-x-2 p-2 rounded-lg border border-gray-200"
                  >
                    <FileText className="h-4 w-4 text-gray-500" />
                    <span className="text-sm font-medium text-gray-900">
                      {filename}
                    </span>
                    <CheckCircle className="h-4 w-4 text-green-500 ml-auto" />
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  )
}

export default E2BSandboxPreview